version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false
    
services:
  poe:
    image: zate75/poedom
    container_name: poe
    restart: always
    labels:
      - traefik.backend=poe
      - traefik.frontend.rule=Host:poerand.zate.org
      - traefik.docker.network=proxy
#      - traefik.port=80
    networks:
      - internal
      - proxy
#
